AWSTemplateFormatVersion: "2010-09-09"
Description: Python Lambda Function deployed via CloudFormation

Parameters:
  FunctionName:
    Type: String
    Description: Name of the Lambda function
    Default: MyPythonFunction
  Handler:
    Type: String
    Description: Lambda function handler (e.g., main.handler)
    Default: main.handler
  Runtime:
    Type: String
    Description: Lambda function runtime
    Default: python3.12
    AllowedValues:
      - python3.8
      - python3.9
      - python3.10
      - python3.11
      - python3.12
  MemorySize:
    Type: Number
    Description: Memory allocated to the Lambda function (in MB)
    Default: 128
  Timeout:
    Type: Number
    Description: Lambda function timeout (in seconds)
    Default: 30
  SourceCodeBucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda function code
  SourceCodeKey:
    Type: String
    Description: Key of the Lambda function code ZIP file in S3

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:log-group:/aws/lambda/*:*:*
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${SourceCodeBucketName}/${SourceCodeKey}"
  PythonLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: !Ref Handler
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref SourceCodeBucketName
          S3_KEY: !Ref SourceCodeKey
      Code:
        ZipFile: |
          import json
          import os
          import zipfile
          import io
          import boto3
          s3 = boto3.client('s3')

          def handler(event, context):
              print("starting")
              print(f"{event=}")
              print(f"{context=}")
              bucket_name = os.environ.get('S3_BUCKET_NAME')
              zip_key = os.environ.get('S3_KEY')
              print(f"{bucket_name=}, {zip_key=}")
              try:
                  # S3 から ZIP ファイルをダウンロード
                  response = s3.get_object(Bucket=bucket_name, Key=zip_key)
                  zip_file = io.BytesIO(response['Body'].read())
                  with zipfile.ZipFile(zip_file, 'r') as zf:
                      for member in zf.namelist():
                          try:
                              file_data = zf.read(member)
                              file_name = os.path.basename(member)
                              print(f"{file_name=}")
                              upload_key = f"unzipped/{os.path.splitext(zip_key)[0]}/{file_name}"
                              s3.put_object(Bucket=bucket_name, Key=upload_key, Body=file_data)
                              print(f"uploaded: {upload_key=}")
                          except Exception as e:
                              print(f"ファイル '{member}' の処理中にエラーが発生しました: {e}")                          
              except Exception as e:
                  print(f"エラーが発生しました: {e}")
              return {
                  'statusCode': 200,
                  'body': json.dumps({'message': "message"})
              }
